#!/bin/bash -x
export CONVERSATION_PASSWORD=$(echo "$CONVERSATION_SERVICE_WATSON_PIZZERIA" | jq -r '.password')
export CONVERSATION_USERNAME=$(echo "$CONVERSATION_SERVICE_WATSON_PIZZERIA" | jq -r '.username')
echo "CONVERSATION_USERNAME == $CONVERSATION_USERNAME"
echo "CONVERSATION_PASSWORD == $CONVERSATION_PASSWORD"
npm start
